name: Default

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  release:
    name: Default
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean shadowJar

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: npm install
        working-directory: .deploy

      - run: |
          npx cdk deploy \
          --context TOKEN_TELEGRAM=${{ secrets.TOKEN_TELEGRAM }} \
          --context CHAT_ID=${{ secrets.CHAT_ID }} \
          --context THREAD_ID=${{ secrets.THREAD_ID }} \
          --require-approval=never
        working-directory: .deploy
